'use client';

import { useState, useEffect } from 'react';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardFooter, CardHeader } from '@/components/ui/card';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Label } from '@/components/ui/label';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { CheckCircle2, XCircle, ChevronRight, ChevronsRight, Sparkles, Loader2, Image as ImageIcon } from 'lucide-react';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import { generateStepByStepExplanation } from '@/ai/flows/generate-step-by-step-explanations';
import { generatePracticeQuestions, GeneratePracticeQuestionsInput } from '@/ai/flows/generate-practice-questions';
import { generateVisualAid } from '@/ai/flows/generate-visual-aid';
import { Skeleton } from '../ui/skeleton';
import { subjects } from '@/lib/data';
import type { PracticeQuestion, Topic, Chapter, Subject } from '@/lib/types';


interface QuizSessionProps {
  topicId: string;
  onFinish: () => void;
}

const findTopicDetails = (topicId: string) => {
    for (const subject of subjects) {
        for (const chapter of subject.chapters) {
            const topic = chapter.topics.find(t => t.id === topicId);
            if (topic) {
                return {
                    subject: subject,
                    chapter: chapter,
                    topic: topic,
                    subtopic: topic.subtopics[0] // Assuming at least one subtopic
                };
            }
        }
    }
    return null;
}


export function QuizSession({ topicId, onFinish }: QuizSessionProps) {
  const [questions, setQuestions] = useState<PracticeQuestion[]>([]);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<string | null>(null);
  const [isAnswered, setIsAnswered] = useState(false);
  const [explanation, setExplanation] = useState<string | null>(null);
  const [isGeneratingExplanation, setIsGeneratingExplanation] = useState(false);
  const [isGeneratingQuestions, setIsGeneratingQuestions] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [visualAidImage, setVisualAidImage] = useState<string | null>(null);
  const [isGeneratingVisualAid, setIsGeneratingVisualAid] = useState(false);
  const [visualAidError, setVisualAidError] = useState<string | null>(null);

  useEffect(() => {
    const fetchQuestion = async () => {
      setIsGeneratingQuestions(true);
      setError(null);
      
      const topicDetails = findTopicDetails(topicId);

      if (!topicDetails) {
          setError("Could not find details for the selected topic.");
          setIsGeneratingQuestions(false);
          return;
      }

      try {
        const input: GeneratePracticeQuestionsInput = {
            subject: topicDetails.subject.name,
            chapter: topicDetails.chapter.name,
            topic: topicDetails.topic.name,
            subtopic: topicDetails.subtopic.name,
            questionType: 'multiple-choice',
        };
        const generatedQuestion = await generatePracticeQuestions(input);
        
        // The flow returns one question, so we wrap it in an array
        const newQuestion: PracticeQuestion = {
            id: `gen-${Date.now()}`,
            question: generatedQuestion.question,
            options: generatedQuestion.options,
            // The generated question doesn't have a correct answer or solution yet.
            // These would need to be handled by another flow or a different process.
            // For now, we'll use placeholder values.
            correctAnswer: generatedQuestion.options?.[0] ?? "",
            solution: "Solution will be generated by AI.",
            topicId: topicId
        };
        setQuestions([newQuestion]);

      } catch (e: any) {
        setError(e.message || "Failed to generate a question.");
      } finally {
        setIsGeneratingQuestions(false);
      }
    };

    fetchQuestion();
  }, [topicId]);

  const resetQuizState = () => {
    setSelectedAnswer(null);
    setIsAnswered(false);
    setExplanation(null);
    setVisualAidImage(null);
    setVisualAidError(null);
  }

  if (isGeneratingQuestions) {
      return (
        <div className="flex flex-col items-center justify-center h-full text-center p-4">
            <Loader2 className="h-8 w-8 animate-spin text-primary mb-4" />
            <p className="text-muted-foreground">Generating a practice question for you...</p>
        </div>
      )
  }

  if (error) {
    return (
        <div className="flex flex-col items-center justify-center h-full text-center p-4">
             <Alert variant="destructive" className="max-w-lg">
                <XCircle className="h-4 w-4" />
                <AlertTitle>Error Generating Question</AlertTitle>
                <AlertDescription>{error}</AlertDescription>
            </Alert>
            <Button onClick={onFinish} className="mt-4">Back to Topics</Button>
        </div>
    )
  }
  
  if (questions.length === 0) {
      return (
          <div className="flex flex-col items-center justify-center h-full text-center p-4">
              <p>No questions available for this topic yet.</p>
              <Button onClick={onFinish} className="mt-4">Back to Topics</Button>
          </div>
      )
  }

  const question = questions[currentQuestionIndex];
  const isCorrect = selectedAnswer === question.correctAnswer;
  const visualAid = PlaceHolderImages.find(img => img.imageHint.includes('diagram') || img.imageHint.includes('figure'));

  const handleSubmit = () => {
    if (selectedAnswer) {
      setIsAnswered(true);
    }
  };

  const handleNext = () => {
    if (currentQuestionIndex < questions.length - 1) {
      setCurrentQuestionIndex(currentQuestionIndex + 1);
      resetQuizState();
    } else {
      onFinish();
    }
  };
  
  const handleGenerateExplanation = async (isOpen: boolean) => {
    if (isOpen && !explanation && !isGeneratingExplanation) {
      setIsGeneratingExplanation(true);
      try {
        const result = await generateStepByStepExplanation({
          question: question.question,
          solution: question.solution,
        });
        setExplanation(result.explanation);
      } catch (error) {
        console.error("Failed to generate explanation:", error);
        setExplanation("Sorry, I couldn't generate an explanation at this time.");
      } finally {
        setIsGeneratingExplanation(false);
      }
    }
  }

  const handleGenerateVisualAid = async () => {
    if (!question) return;
    setIsGeneratingVisualAid(true);
    setVisualAidError(null);
    setVisualAidImage(null);
    try {
      const result = await generateVisualAid({ description: `A visual diagram for the following problem: ${question.question}` });
      setVisualAidImage(result.imageDataUri);
    } catch (e: any) {
      setVisualAidError(e.message || 'An unexpected error occurred while generating the visual aid.');
    } finally {
      setIsGeneratingVisualAid(false);
    }
  };

  return (
    <div className="p-4 md:p-8 flex justify-center">
      <Card className="w-full max-w-3xl">
        <CardHeader>
          <p className="text-sm text-muted-foreground">Question {currentQuestionIndex + 1} of {questions.length}</p>
          <p className="text-lg">{question.question}</p>
        </CardHeader>
        <CardContent className="space-y-6">
          {question.visualAidUrl && visualAid && (
             <div className="my-4 relative h-64">
                <Image
                    src={visualAid.imageUrl}
                    alt={visualAid.description}
                    fill
                    className="rounded-md object-contain"
                    data-ai-hint={visualAid.imageHint}
                />
            </div>
          )}

          <RadioGroup 
            value={selectedAnswer ?? undefined}
            onValueChange={setSelectedAnswer} 
            disabled={isAnswered}
          >
            {question.options?.map((option, index) => (
              <div key={index} className="flex items-center space-x-2">
                <RadioGroupItem value={option} id={`option-${index}`} />
                <Label htmlFor={`option-${index}`}>{option}</Label>
              </div>
            ))}
          </RadioGroup>

          {isAnswered && (
            <Alert variant={isCorrect ? "default" : "destructive"} className={isCorrect ? "border-green-500" : ""}>
              {isCorrect ? (
                <CheckCircle2 className="h-4 w-4" />
              ) : (
                <XCircle className="h-4 w-4" />
              )}
              <AlertTitle>{isCorrect ? 'Correct!' : 'Incorrect'}</AlertTitle>
              <AlertDescription>
                {isCorrect ? 'Great job!' : `The correct answer is ${question.correctAnswer}.`}
              </AlertDescription>
            </Alert>
          )}

          {isAnswered && (
            <Accordion type="single" collapsible onValueChange={(value) => handleGenerateExplanation(value === 'solution')}>
              <AccordionItem value="solution">
                <AccordionTrigger>View AI-Powered Explanation</AccordionTrigger>
                <AccordionContent>
                  <div className="prose prose-sm max-w-none text-foreground dark:prose-invert space-y-4">
                    <p>
                        <span className="font-semibold">Original Solution:</span> {question.solution}
                    </p>
                    <div className='border-t pt-4 mt-4'>
                        <h4 className='font-semibold flex items-center gap-2'><Sparkles className="w-4 h-4 text-primary" /> Step-by-step Explanation</h4>
                        {isGeneratingExplanation && (
                            <div className='space-y-2 mt-2'>
                                <Skeleton className="h-4 w-5/6" />
                                <Skeleton className="h-4 w-full" />
                                <Skeleton className="h-4 w-4/6" />
                            </div>
                        )}
                        {explanation && (
                          <div className="space-y-4">
                            <p>{explanation}</p>
                            <Button variant="outline" size="sm" onClick={handleGenerateVisualAid} disabled={isGeneratingVisualAid}>
                                {isGeneratingVisualAid ? (
                                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                ) : (
                                    <ImageIcon className="mr-2 h-4 w-4" />
                                )}
                                {isGeneratingVisualAid ? 'Generating...' : 'Generate Visual Diagram'}
                            </Button>
                             {visualAidError && (
                                <Alert variant="destructive">
                                    <XCircle className="h-4 w-4" />
                                    <AlertTitle>Error</AlertTitle>
                                    <AlertDescription>{visualAidError}</AlertDescription>
                                </Alert>
                            )}
                            {isGeneratingVisualAid && (
                              <div className='flex flex-col items-center justify-center pt-4'>
                                <Skeleton className="h-[250px] w-[250px] rounded-lg" />
                                <p className="text-muted-foreground text-sm mt-2">Generating diagram...</p>
                              </div>
                            )}
                            {visualAidImage && (
                              <div className="relative aspect-square w-full max-w-md mx-auto mt-4">
                                <Image
                                  src={visualAidImage}
                                  alt="Generated visual aid for the question"
                                  fill
                                  className="rounded-lg object-contain"
                                />
                              </div>
                            )}
                          </div>
                        )}
                    </div>
                  </div>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          )}
        </CardContent>
        <CardFooter>
          {!isAnswered ? (
            <Button onClick={handleSubmit} disabled={!selectedAnswer} className="ml-auto">
              Submit <ChevronRight/>
            </Button>
          ) : (
            <Button onClick={handleNext} className="ml-auto">
              {currentQuestionIndex < questions.length - 1 ? 'Next Question' : 'Finish Session'}
              <ChevronsRight />
            </Button>
          )}
        </CardFooter>
      </Card>
    </div>
  );
}
